compile:
  # Choosing to run compilation tests on 2 different Arduino platforms
  platforms:
    - esp8266
    - esp32
    - UNO

packages:
  adafruit:samd:
    url: https://adafruit.github.io/arduino-board-index/package_adafruit_index.json

